### ISSUE TITLE
Full-text searching

### ISSUE THREAD

**Issue by grayxr** [ytsuyuzaki/google-drive-client-php#5]
Hi, this is a nice package - thank you so much! I was wondering if I could perform a search that would search the text in all of my public drive files.

I see that there is a class in the Google_DriveService file:

```
 class Google_DriveFileIndexableText 
```

that has the function 'getText()'.

I'm wondering how I could implement that to get the text of ALL my drive files that contain text - and then maybe filter it by adding query parameters.

**Comment by ytsuyuzaki** [comment]
Hi jgrayillustrate, I'm glad you were using this package.
To add the functionality of the text search it is a good idea.

The package you want to add a Spreadsheet to Google Drive is so, because it was something that was made ​​for, function is not enough to become With frequently.
I want to sent the pull request with new features added all means.

Class to be added

```
Soramugi\GoogleDrive\File
```

Is something I think we better.
